In [1]:
url = 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/DEMO_R_D3DENS?lang=EN'

In [44]:
url = 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/apri_pi20_outa?lang=en'

In [45]:
import requests

In [46]:
res = requests.get(url)

In [47]:
data = res.json()

In [51]:
len(data['value'])

23790

In [59]:
data['dimension']['product'].keys()

dict_keys(['label', 'category'])

https://www.kaggle.com/code/crischir/eurostat-api

In [63]:
pd.DataFrame(data['dimension']['product']['category'])

        index                                              label
010000      0                          Cereals (including seeds)
011000      1                                    Wheat and spelt
...       ...                                                ...
140000    109  Agricultural goods output (100000+130000), inc...
141000    110  Agricultural goods output  (101000+130000), ex...

[111 rows x 2 columns]

In [18]:
import pandas as pd

In [25]:
pd.DataFrame(data['dimension'])

,freq,product,p_adj,unit,geo,time
label,Time frequency,Products,Price adjustment,Unit of measure,Geopolitical entity (reporting),Time
category,"{'index': {'A': 0}, 'label': {'A': 'Annual'}}","{'index': {'010000': 0, '011000': 1, '011100':...","{'index': {'NI': 0, 'RI': 1}, 'label': {'NI': ...","{'index': {'I20': 0, 'PCH_PRE': 1}, 'label': {...","{'index': {'EU27_2020': 0, 'BE': 1, 'BG': 2, '...","{'index': {'2020': 0, '2021': 1, '2022': 2, '2..."

In [28]:
values = data['value']

In [30]:
data['dimension']

{'freq': {'label': 'Time frequency',
  'category': {'index': {'A': 0}, 'label': {'A': 'Annual'}}},
 'product': {'label': 'Products',
  'category': {'index': {'010000': 0,
    '011000': 1,
    '011100': 2,
    '011200': 3,
    '012000': 4,
    '013000': 5,
    '013100': 6,
    '013200': 7,
    '014000': 8,
    '015000': 9,
    '016000': 10,
    '019000': 11,
    '020000': 12,
    '021000': 13,
    '021100': 14,
    '021200': 15,
    '021300': 16,
    '021900': 17,
    '022000': 18,
    '023000': 19,
    '024000': 20,
    '029000': 21,
    '029100': 22,
    '029200': 23,
    '029900': 24,
    '030000': 25,
    '032000': 26,
    '039000': 27,
    '039100': 28,
    '039200': 29,
    '039300': 30,
    '039900': 31,
    '040000': 32,
    '041000': 33,
    '041100': 34,
    '041200': 35,
    '041900': 36,
    '041910': 37,
    '041920': 38,
    '041930': 39,
    '041940': 40,
    '041950': 41,
    '041960': 42,
    '041970': 43,
    '041980': 44,
    '041990': 45,
    '041999': 46,
    '042000': 47,
    '050000': 48,
    '051000': 49,
    '051100': 50,
    '051200': 51,
    '052000': 52,
    '059000': 53,
    '060000': 54,
    '061000': 55,
    '061100': 56,
    '061200': 57,
    '061300': 58,
    '061900': 59,
    '061910': 60,
    '061920': 61,
    '061930': 62,
    '061940': 63,
    '061941': 64,
    '061942': 65,
    '061990': 66,
    '062000': 67,
    '062100': 68,
    '062200': 69,
    '062300': 70,
    '062900': 71,
    '063000': 72,
    '064000': 73,
    '064100': 74,
    '064900': 75,
    '065000': 76,
    '065100': 77,
    '065900': 78,
    '070000': 79,
    '073000': 80,
    '073100': 81,
    '073200': 82,
    '078000': 83,
    '080000': 84,
    '090000': 85,
    '091000': 86,
    '092000': 87,
    '099000': 88,
    '100000': 89,
    '101000': 90,
    '110000': 91,
    '111000': 92,
    '111100': 93,
    '111200': 94,
    '112000': 95,
    '113000': 96,
    '114000': 97,
    '115000': 98,
    '115100': 99,
    '115900': 100,
    '119000': 101,
    '120000': 102,
    '121000': 103,
    '121100': 104,
    '121900': 105,
    '122000': 106,
    '129000': 107,
    '130000': 108,
    '140000': 109,
    '141000': 110},
   'label': {'010000': 'Cereals (including seeds)',
    '011000': 'Wheat and spelt',
    '011100': 'Soft wheat and spelt',
    '011200': 'Durum wheat',
    '012000': 'Rye and meslin',
    '013000': 'Barley',
    '013100': 'Feed barley',
    '013200': 'Malting barley',
    '014000': 'Oats and summer cereal mixtures',
    '015000': 'Grain maize',
    '016000': 'Rice',
    '019000': 'Other cereals',
    '020000': 'Industrial crops',
    '021000': 'Oil seeds and oleaginous fruits (including seeds)',
    '021100': 'Rape and turnip rape seed',
    '021200': 'Sunflower',
    '021300': 'Soya',
    '021900': 'Other oleaginous products',
    '022000': 'Protein crops (including seeds)',
    '023000': 'Raw tobacco',
    '024000': 'Sugar beet',
    '029000': 'Other industrial crops',
    '029100': 'Fibre plants',
    '029200': 'Hops',
    '029900': 'Other industrial crops: others',
    '030000': 'Forage plants',
    '032000': 'Fodder root crops (including forage beet)',
    '039000': 'Other forage plants',
    '039100': 'Hay',
    '039200': 'Straw',
    '039300': 'Silage',
    '039900': 'Other forage plants: others',
    '040000': 'Vegetables and horticultural products',
    '041000': 'Fresh vegetables',
    '041100': 'Cauliflower',
    '041200': 'Tomatoes',
    '041900': 'Other fresh vegetables',
    '041910': 'Cabbage',
    '041920': 'Lettuce',
    '041930': 'Spinach',
    '041940': 'Cucumbers',
    '041950': 'Carrots',
    '041960': 'Onions',
    '041970': 'Green beans',
    '041980': 'Pulses',
    '041990': 'Peas',
    '041999': 'Other fresh vegetables: other',
    '042000': 'Plants and flowers',
    '050000': 'Potatoes (including seeds)',
    '051000': 'Potatoes for consumption',
    '051100': 'Early potatoes',
    '051200': 'Main crop potatoes',
    '052000': 'Seed potatoes',
    '059000': 'Other potatoes',
    '060000': 'Fruits',
    '061000': 'Fresh fruit (excluding citrus fruit and grapes)',
    '061100': 'Dessert apples',
    '061200': 'Dessert pears',
    '061300': 'Peaches',
    '061900': 'Other fresh fruit, nuts and dried fruit',
    '061910': 'Cherries',
    '061920': 'Plums',
    '061930': 'Strawberries',
    '061940': 'Nuts and dried fruit',
    '061941': 'Nuts',
    '061942': 'Dried fruit',
    '061990': 'Other fresh fruit: other',
    '062000': 'Citrus fruit',
    '062100': 'Sweet oranges',
    '062200': 'Mandarins',
    '062300': 'Lemons',
    '062900': 'Other citrus fruits',
    '063000': 'Tropical fruit',
    '064000': 'Grapes',
    '064100': 'Dessert grapes',
    '064900': 'Other grapes, fresh',
    '065000': 'Olives',
    '065100': 'Table olives',
    '065900': 'Other olives',
    '070000': 'Wine',
    '073000': 'PDO and PGI',
    '073100': 'PDO',
    '073200': 'PGI',
    '078000': 'Wines, other than PDO or PGI',
    '080000': 'Olive oil',
    '090000': 'Other crop products',
    '091000': 'Vegetable materials used primarily for plaiting',
    '092000': 'Seeds',
    '099000': 'Other crop products: others',
    '100000': 'Crop output (010000 to 090000), including fruits (060000) and vegetables (040000)',
    '101000': 'Crop output (010000 to 090000), excluding fruits (060000) and vegetables (040000)',
    '110000': 'Animals',
    '111000': 'Cattle',
    '111100': 'Cattle excluding calves',
    '111200': 'Calves',
    '112000': 'Pigs',
    '113000': 'Equines',
    '114000': 'Sheep and goats',
    '115000': 'Poultry',
    '115100': 'Chickens',
    '115900': 'Other poultry',
    '119000': 'Other animals',
    '120000': 'Animal products',
    '121000': 'Milk',
    '121100': "Cows' milk",
    '121900': 'Other milk types',
    '122000': 'Eggs',
    '129000': 'Other animal products',
    '130000': 'Animal output (110000+120000)',
    '140000': 'Agricultural goods output (100000+130000), including fruits (060000) and vegetables (040000)',
    '141000': 'Agricultural goods output  (101000+130000), excluding fruits (060000) and vegetables (040000)'}}},
 'p_adj': {'label': 'Price adjustment',
  'category': {'index': {'NI': 0, 'RI': 1},
   'label': {'NI': 'Nominal index', 'RI': 'Real index'}}},
 'unit': {'label': 'Unit of measure',
  'category': {'index': {'I20': 0, 'PCH_PRE': 1},
   'label': {'I20': 'Index, 2020=100',
    'PCH_PRE': 'Percentage change on previous period'}}},
 'geo': {'label': 'Geopolitical entity (reporting)',
  'category': {'index': {'EU27_2020': 0,
    'BE': 1,
    'BG': 2,
    'CZ': 3,
    'DK': 4,
    'DE': 5,
    'EE': 6,
    'IE': 7,
    'EL': 8,
    'HR': 9,
    'CY': 10,
    'LV': 11,
    'LT': 12,
    'LU': 13,
    'HU': 14,
    'MT': 15,
    'NL': 16,
    'AT': 17,
    'PL': 18,
    'PT': 19,
    'RO': 20,
    'SI': 21,
    'SK': 22,
    'FI': 23},
   'label': {'EU27_2020': 'European Union - 27 countries (from 2020)',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'CZ': 'Czechia',
    'DK': 'Denmark',
    'DE': 'Germany',
    'EE': 'Estonia',
    'IE': 'Ireland',
    'EL': 'Greece',
    'HR': 'Croatia',
    'CY': 'Cyprus',
    'LV': 'Latvia',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'HU': 'Hungary',
    'MT': 'Malta',
    'NL': 'Netherlands',
    'AT': 'Austria',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'FI': 'Finland'}}},
 'time': {'label': 'Time',
  'category': {'index': {'2020': 0, '2021': 1, '2022': 2, '2023': 3},
   'label': {'2020': '2020', '2021': '2021', '2022': '2022', '2023': '2023'}}}}

In [12]:
pd.DataFrame(data['value'])

ValueError: If using all scalar values, you must pass an index

In [9]:
pd.json_normalize(data)

,version,class,label,source,updated,id,size,value.61468,value.61469,value.61470,...,extension.status.label.b,extension.status.label.be,extension.status.label.ep,extension.status.label.bep,extension.status.label.p,extension.status.label.bp,extension.positions-with-no-data.freq,extension.positions-with-no-data.unit,extension.positions-with-no-data.geo,extension.positions-with-no-data.time
0,2.0,dataset,Population density by NUTS 3 region,ESTAT,2024-03-26T23:00:00+0100,"[freq, unit, geo, time]","[1, 1, 2031, 33]",100.7,100.6,100.4,...,break in time series,"break in time series, estimated","estimated, provisional","break in time series, estimated, provisional",provisional,"break in time series, provisional",[],[],[],[]